name: "nodejs-app-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false
# =========================== Filebeat Inputs ====================== #
filebeat.inputs:
- type: log
  scan_frequency: 1s

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /src/logs/*.log
  fields:
    - service: nodejs-app
  fields_under_root: true
  json:
    keys_under_root: true
    overwrite_keys: true
    message_key: 'message'

# =========================== Elasticsearch Output ====================== #
output.elasticsearch:
# Array of hosts to connect to.
  hosts: ["elasticsearch:9200"]
  index: "nodejs-app"
